const BASE_URL = "http://localhost:1234"
export const API_URLS = {
  LOGIN_URL: BASE_URL+'/api/login',
  CLIENTS_URL: BASE_URL+'/api/clients',
  CLIENTS_PAIEMENTS_URL: BASE_URL+'/api/paiements',
  VILLES_URL: BASE_URL+'/api/villes',
  FORNISSEURS_URL: BASE_URL+'/api/fornisseurs',
  UTILISATEURS_URL: BASE_URL+'/api/utilisateurs',
  ROLES_URL: BASE_URL+'/api/roles',
  BANQUES_URL: BASE_URL+'/api/banques',
  ETATS_URL: BASE_URL+'/api/etats',
  TYPES_URL: BASE_URL+'/api/types',
  VENDEURS_URL: BASE_URL+'/api/vendeurs',
  TRANSPORTS_URL:BASE_URL+'/api/transports',
  HISTORIQUE_URL: BASE_URL+'/api/historiques',
  ALERTS_FOURNISSEUR_URL: BASE_URL+'/api/paiements/alerts/fournisseurs',
  ALERTS_CLIENTS_URL: BASE_URL+'/api/paiements/alerts/clients',
  AUTORITE_URL: BASE_URL+'/api/autorites',
  STATISTICS_CLIENTS_URL: BASE_URL+'/api/statistiques/clients',
  STATISTICS_FOURNISSEUR_URL: BASE_URL+'/api/statistiques/fournisseurs',
  STATISTICS_CLIENTS_BY_VILLES_URL: BASE_URL+'/api/statistiques/client-ville',
  STATISTICS_CLIENTS_BY_INCIDENT_URL: BASE_URL+'/api/statistiques/client-incident',
  STATISTICS_CLIENTS_BY_CHIFFRE_URL: BASE_URL+'/api/statistiques/client-chiffre',
  STATISTICS_VENDEUR: BASE_URL+'/api/statistiques/vendeur',
  ARTICLES_URL: BASE_URL+'/api/articles',
  COMMANDES_URL: BASE_URL+'/api/commandes',
  FACTURES_URL: BASE_URL+'/api/factures',
  TRAJETS_URL: BASE_URL+'/api/trajets',
  VERSEMENTS_URL: BASE_URL+'/api/versements',
  LIGNE_DE_COMMANDE_URL: BASE_URL+'/api/ligne-commandes',
  TRAJETS_SUBS_URL: BASE_URL+'/api/trajetsSubs',

}
