export const API_URLS = {
  LOGIN_URL: 'http://localhost:1234/api/login',
  CLIENTS_URL: 'http://localhost:1234/api/clients',
  CLIENTS_PAIEMENTS_URL: 'http://localhost:1234/api/paiements',
  VILLES_URL: 'http://localhost:1234/api/villes',
  FORNISSEURS_URL: 'http://localhost:1234/api/fornisseurs',
  UTILISATEURS_URL: 'http://localhost:1234/api/utilisateurs',
  ROLES_URL: 'http://localhost:1234/api/roles',
  BANQUES_URL: 'http://localhost:1234/api/banques',
  ETATS_URL: 'http://localhost:1234/api/etats',
  TYPES_URL: 'http://localhost:1234/api/types',
  VENDEURS_URL: 'http://localhost:1234/api/vendeurs',
  TRANSPORTS_URL:'http://localhost:1234/api/transports',
  HISTORIQUE_URL: 'http://localhost:1234/api/historiques',
  ALERTS_FOURNISSEUR_URL: 'http://localhost:1234/api/paiements/alerts/fournisseurs',
  ALERTS_CLIENTS_URL: 'http://localhost:1234/api/paiements/alerts/clients',
  AUTORITE_URL: 'http://localhost:1234/api/autorites',
  STATISTICS_CLIENTS_URL: 'http://localhost:1234/api/statistiques/clients',
  STATISTICS_FOURNISSEUR_URL: 'http://localhost:1234/api/statistiques/fournisseurs',
  STATISTICS_CLIENTS_BY_VILLES_URL: 'http://localhost:1234/api/statistiques/client-ville',
  STATISTICS_CLIENTS_BY_INCIDENT_URL: 'http://localhost:1234/api/statistiques/client-incident',
  STATISTICS_CLIENTS_BY_CHIFFRE_URL: 'http://localhost:1234/api/statistiques/client-chiffre',
  STATISTICS_VENDEUR: 'http://localhost:1234/api/statistiques/vendeur',
  ARTICLES_URL: 'http://localhost:1234/api/articles',
  COMMANDES_URL: 'http://localhost:1234/api/commandes',
  FACTURES_URL: 'http://localhost:1234/api/factures',
  TRAJETS_URL: 'http://localhost:1234/api/trajets',
  VERSEMENTS_URL: 'http://localhost:1234/api/versements',
  LIGNE_DE_COMMANDE_URL: 'http://localhost:1234/api/ligne-commandes',
  TRAJETS_SUBS_URL: 'http://localhost:1234/api/trajetsSubs',

}
